[feat] OAuth 카카오 로그인 수정, 회원 가입 기능 구현 및 테스트 코드 리팩터링
UPbrella/UPbrella_back pull request #98
Opened 2023-08-01 12:52 UTC by Gwonwoo-Nam

## 🟢 구현내용

- #97 

## 🧩 고민과 해결과정

- API 명세만 변경안에 따라 고치려고했는데 RestDocs 특성상 테스트가 얽혀있어서 테스트 fail되는 코드를 PR올릴수는 없을 것 같아 고치다보니 결국 한 가지 기능에 집중하게 되어버렸습니다..
- Naver 로그인 관련 코드를 삭제했고 로그인은 변경된 로직에 맞게 코드 수정하고, 테스트 코드를 추가했습니다.
- 간단하게 로그인 완료 시 회원 가입이 완료될 때까지 auth 토큰을 세션에 유지하다가, 회원가입이 완료되면 auth 토큰을 세션에서 제거하고 회원 ID로 세션을 유지하는 방식입니다.
- 이렇게 구현한 이유는 oauth로 로그인 된 상태를 세션에 저장해야 회원가입이 가능하기 때문입니다
- 인터셉터는 일단 oauth path를 제외하고 전부 막아두었는데 추가로 설정이 필요할거같구요, 커스텀 예외도 일단 한가지만 추가해놓았는데 점점 확장시키고 예외 처리, 적절한 에러 코드 반환도 할 수 있게 할 예정입니다.

2023-08-01 13:42 UTC, birdieHyun requested changes
고생하셨습니다

2023-08-01 13:42 UTC, birdieHyun commented on src/main/java/upbrella/be/login/controller/LoginController.java
여기서는 롬복을 사용하지 않은 이유가 있나요?

2023-08-01 13:42 UTC, birdieHyun commented on src/main/java/upbrella/be/login/interceptor/OAuthLoginInterceptor.java
> +
request.getSession()을 해버리면 세션이 없는 경우에도 세션이 생겨버리는데, 
request.getSession(false) 를 통해 세션이 없는 경우를 예외처리 하는건 어떤가요?

2023-08-01 13:42 UTC, birdieHyun commented on src/main/java/upbrella/be/login/dto/response/KakaoLoginResponse.java
>  }
public class KakaoLoginResponse {  

    // 공백
    private Long id;  

}  


컨벤션 지켜주세요!

2023-08-01 13:42 UTC, birdieHyun commented on src/main/java/upbrella/be/login/dto/token/KakaoOauthInfo.java
>  public class KakaoOauthInfo implements CommonOauthInfo {
CommonOauthInfo의 경우 Kakao, Naver 두 로그인을 지원하기 위해서 만든건데, 프로젝트 특성상 카카오 로그인만 지원할거니 CommonOauthInfo는 삭제해도 될 것 같습니다

2023-08-01 13:42 UTC, birdieHyun commented on src/main/java/upbrella/be/login/service/OauthLoginService.java
>      }
여기도 시그니처 다음 한 줄 공백 해주세요!

2023-08-01 13:42 UTC, birdieHyun commented on src/main/java/upbrella/be/user/entity/User.java
> +    public static User createNewUser(long socialId) {
User entity도 시그니처 이후 공백 수정해주세요

2023-08-01 13:42 UTC, birdieHyun commented on src/main/java/upbrella/be/user/repository/UserRepository.java
> +    boolean existsBySocialId(Long socialId);
여기도 한 줄 띄우면 좋을것 같습니다

2023-08-01 13:42 UTC, birdieHyun commented on src/main/java/upbrella/be/user/service/UserService.java
> +        return userRepository.save(User.createNewUser(socialId, joinRequest)).getId();
userRepository.save() 와 getId() 를 분리하면 가독성이 더 좋아지지 않을까요?

2023-08-01 13:42 UTC, birdieHyun commented on src/test/java/upbrella/be/login/controller/LoginControllerTest.java
>      @Override
한 줄 공백 유지하면 좋을것 같습니다

2023-08-01 13:58 UTC, Gwonwoo-Nam commented on src/main/java/upbrella/be/login/controller/LoginController.java
Common에서 Kakao로 바꾸는 과정에서 그대로 남았네요 lombok으로 변경하겠습니다

2023-08-01 14:04 UTC, Gwonwoo-Nam commented on src/main/java/upbrella/be/login/interceptor/OAuthLoginInterceptor.java
> +
세션이 생긴다는걸 몰랐네요 null체크를 한번 더 넣어줬습니다.

2023-08-01 14:05 UTC, Gwonwoo-Nam commented on src/main/java/upbrella/be/login/dto/token/KakaoOauthInfo.java
>  public class KakaoOauthInfo implements CommonOauthInfo {
삭제했습니다

2023-08-01 14:08 UTC, Gwonwoo-Nam commented on src/main/java/upbrella/be/user/service/UserService.java
> +        return userRepository.save(User.createNewUser(socialId, joinRequest)).getId();
분리했습니다

2023-08-02 04:50 UTC, birdieHyun approved these changes
고생하셨습니다

2023-08-02 06:01 UTC, acceptor-gyu commented on src/main/java/upbrella/be/error/controller/ErrorController.java
> +    @RequestMapping(value = "/error", method = {RequestMethod.POST, RequestMethod.GET, RequestMethod.PATCH, RequestMethod.DELETE})
여기는 한 줄을 띄지 않은 이유가 있나요?

2023-08-02 06:01 UTC, acceptor-gyu commented on src/main/java/upbrella/be/error/controller/ErrorController.java
> +                        null));
500 에러를 던지는게 올바른 방향인가요?

2023-08-02 06:02 UTC, acceptor-gyu approved these changes

2023-08-02 06:15 UTC, merged